---
galaxy_info:
  author: Ygal Blum, Bob Mader
  description: Revert to snapshots previously created using the snapshot_create role
  company: Red Hat
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []
dependencies: []
...
