- name: Verify that all snapshots are active
  ansible.builtin.include_tasks: verify_snapshot_active.yml
  loop: "{{ lvm_snapshots_snapshots }}"

- name: Restore boot backup
  ansible.builtin.unarchive:
    remote_src: true
    src: "/root/boot-backup-{{ lvm_snapshots_set_name }}.tgz"
    dest: /boot
  when: lvm_snapshots_boot_backup

- name: Revert to snapshots
  ansible.builtin.command: "lvconvert --merge /dev/{{ item.vg_name }}/{{ item.lv_name }}"
  loop: "{{ lvm_snapshots_snapshots }}"
  changed_when: false

- name: Reboot
  ansible.builtin.reboot:

- name: Remove boot backup
  ansible.builtin.file:
    path: "/root/boot-backup-{{ lvm_snapshots_set_name }}.tgz"
    state: absent
  when: lvm_snapshots_boot_backup

- name: Wait for the snapshot to drain
  ansible.builtin.command: "lvs --select 'lv_name = {{ item.origin }}' --reportformat json"
  register: _lv_drain_check
  until: (_lv_drain_check.stdout | from_json).report[0].lv[0].data_percent == ""
  retries: 20
  delay: 30
  loop: "{{ lvm_snapshots_snapshots }}"
  changed_when: false
