---
galaxy_info:
  author: Ygal Blum, Bob Mader
  description: Included by the shrink_lv and bigboot roles to run an atomic flow of building and using a temporary initramfs in a reboot and restoring the original one
  company: Red Hat
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []
dependencies: []
...
